repos:
  - repo: https://github.com/psf/black
    rev: 23.9.1  # Replace with the latest version of Black
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0  # Replace with the latest version of isort
    hooks:
      - id: isort
        args:
          - --profile=black

  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0  # Replace with the latest version of flake8
    hooks:
      - id: flake8
        args:
          - --max-line-length=88  # To match Black's default line length
          - --extend-ignore=E203  # To avoid conflicts with Black
          - --ignore=E722
